### ISSUE TITLE
Cannot view my cluster

### ISSUE THREAD

**Issue by arielpontes** [yahoo/CMAK#835]
Hi, I'm new to Kafka so this might be me misunderstanding something, but I'm just trying to do a "Hello world" using Kafka in an existing project and something is not working. Currently I have this in my docker-compose:

```
version: '3.7'

services:
  # ... 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "mytopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
# ...
```

When I access localhost:9000, I see the interface, but I see nothing in my list of clusters. How can I make sure the cluster, topics, etc, are all created automatically when I run `docker-compose up`? Is this possible?
